sudo: false
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'

install:
  - npm install

script:
  - npm test

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/test

branches:
  only:
    - master
    - develop