sudo: false
language: node_js
node_js:
  - 8.11.1

install:
  - npm install

script:
  - npm test

services:
  - couchdb

before_script:
  - curl -X PUT $TEST_DB_PROTOCOL://$TEST_DB_HOST:$TEST_DB_PORT/$NODE_ENV
  - curl -X PUT $TEST_DB_PROTOCOL://$TEST_DB_HOST:$TEST_DB_PORT/_config/admins/$TEST_DB_USERNAME -d "'password'"
  - curl -X GET $TEST_DB_PROTOCOL://$TEST_DB_USERNAME:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/_all_dbs


branches:
  only:
    - master
    - develop