sudo: false
language: node_js
node_js:
  - 8.11.1

install:
  - npm install

script:
  - npm test

services:
  - couchdb

before_script:
  - npm config set strict-ssl false
  - curl -X PUT $TEST_DB_PROTOCOL://$TEST_DB_HOST:$TEST_DB_PORT/test
  - curl -X PUT $TEST_DB_PROTOCOL://$TEST_DB_HOST:$TEST_DB_PORT/_config/admins/admin -d '"'"$TEST_DB_PASSWORD"'"'
  - curl -X GET $TEST_DB_PROTOCOL://$TEST_DB_USERNAME:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/_all_dbs
  - node setup/createObjectIndex

after_success:
  - echo 'stress testing index...'
  - ./node_modules/node-ab/bin/nab http://127.0.0.1:$PORT/
  - echo 'stress testing get object'
  - ./node_modules/node-ab/bin/nab http://127.0.0.1:$PORT/object/mykey

branches:
  only:
    - master
    - develop
