sudo: false
language: node_js
node_js:
  - 8.11.1

install:
  - npm install

script:
  - npm test

services:
  - couchdb

before_script:
  - curl -X PUT http://localhost:5984/test
  - curl -X PUT http://localhost:5984/_config/admins/admin -d "'password'"
  - curl -X GET http://admin:password@localhost:5984/_all_dbs


branches:
  only:
    - master
    - develop