sudo: false
language: node_js
node_js:
  - 8.11.1

install:
  - npm install

script:
  - npm test

services:
  - couchdb

before_script:
  - curl -X PUT $TEST_DB_PROTOCOL://$TEST_DB_HOST:$TEST_DB_PORT/test
  - curl -X PUT $TEST_DB_PROTOCOL://$TEST_DB_HOST:$TEST_DB_PORT/_config/admins/admin -d '"'"$TEST_DB_PASSWORD"'"'
  - curl -X GET $TEST_DB_PROTOCOL://$TEST_DB_USERNAME:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/_all_dbs
  - curl -X POST $TEST_DB_PROTOCOL://$TEST_DB_USERNAME:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/$NODE_ENV/_index -H 'Content-Type:application/json' -d '{"index":{"fields":["timestamp"]},"name":"timestamp-index","type":"json"}'



branches:
  only:
    - master
    - develop